spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        use_sql_comments: true
  data:
    web:
      pageable:
        default-page-size: 10

logging:
  level:
    org.hibernate.sql : debug